% Filename:     buildSpace.m
% Author:       Federico MATTA & Florent PERRONIN
% Last update:  11/03/2005
% Copyright:    Institut Eurecom
%
% [Means, Space, Eigenvalues] = buildSpace(Vectors)
%
% It computes the average 'Means' of all vectors in 'Vectors' and the
% eigenvalues 'Eigenvalues' and eigenspace 'Space' generated by these
% vectors; the method used is Singular Value Decomposition (SVD).
% Eigenvectors are automatically sorted by their contribution,
% i.e. eigenvectors which correspond to the largest eigenvalues are ranked
% first in 'Space'.
%
% Usage example:
% [Means, Space, Eigenvalues] = buildSpace(Vectors);

function [Means, Space, Eigenvalues] = buildSpace(Vectors)

error(nargchk(1, 1, nargin))


% Execution: computing the eigenspace using SVD...
VectorsSizes = size(Vectors);
Means = mean(Vectors);
CenteredVectors = (Vectors - repmat(Means, VectorsSizes(1), 1));
[U, S, V] = svd(CenteredVectors);
Space = V(: , 1 : VectorsSizes(1))';
Eigenvalues = diag(S);